### ISSUE TITLE
Video and SD Card Use

### ISSUE THREAD

**Issue by spairo1741** [DGxInfinitY/Teensy3.2#1]
Is there any video from youtube?

**Comment by DGxInfinitY** [comment]
No not as of now, if you would like to see one I would be willing to make a video on the current release for you...

**Comment by spairo1741** [comment]
After the build I have a message and only 2000 bytes of RAM on local variables?

"Sketch uses 21924 bytes (8%) of program storage space. Maximum is 262144 bytes.
Global variables use 63344 bytes (96%) of dynamic memory, leaving 2192 bytes for local variables. Maximum is 65536 bytes. "
Teensy 3.2 Serial. 72 MHz, Faster, US English on COM13

**Comment by DGxInfinitY** [comment]
That is right, for a little explanation, the sketch is very small in comparison to what direct space we have for the runtime code. Dynamic Memory is RAM(Random Access Memory), I left ~4% for the system and the rest dedicated to your programs that you can write, you have as much EPROM as you do ram so if you fill up your ram you could, in theory, offload to EEPROM for more space, but it is slower and there is nothing I can really do about that on your end as It requires replacement of EPROM in hardware. I am working on an explanational video so that you can see for yourself. And for the sake of accuracy are you on Windows, Mac, or Linux?

**Comment by spairo1741** [comment]
I am working on windows 7 x32 and x64
Is it possible to add more RAM, something like XMEM for ATMega when you add SRAM 23LC1024 (128 x 8)?
The tiny basic system must see this extra RAM as its system.
`HELLO
Teensy TinyBASICPlus v1.1
58341 bytes free.
2048 EEProm bytes total.
OK
>list
OK
>mem
58341 bytes free.
2048 EEProm bytes total.
1989 EEProm bytes available.
>eload`

**Comment by spairo1741** [comment]
maybe not working INPUT no waiting for press key.

> 
>list
10 A=10
15 Z= 0
20 INPUT Z
30 Y = 120
40 PRINT A+Z
50 CHP 1
60 DELAY 2000
70 PRINT "?"
OK
>run
109
?
OK
>

**Comment by DGxInfinitY** [comment]
So I see, INPUT doesn't function properly. I think I may have found the problem, Just give me a second to compile and test and then I will give you the code and the compiled binary. Thanks for testing, it helps to work out the bugs!

**Comment by DGxInfinitY** [comment]
A new update is out for code so make sure to check it out, also I am in the process of making a video explaining how to flash and use the code on your teensy. I am on Linux but I will use cross-platform tools so that you can follow along on Windows, Mac, or Linux. Also thanks so much for letting me know about the INPUT command not working it helps a ton when users find problems with the code, it helps fix the problems. @spairo1741

**Comment by spairo1741** [comment]
I have trouble initializing a micro SD CARD under Tiny Basic Teensy T3.2. I use the library SdFatBeta20130621  and the Quick Start program to check the correctness of the wire (links) and it is look good.

"HELLO
Teensy TinyBASICPlus v1.1
SD card error.
57311 bytes free.
2048 EEProm bytes total.
OK "

and test SD card

" 
Enter the chip select pin number: 10
Card successfully initialized.
Card size: 7948 MB (MB = 1,000,000 bytes)
Volume is FAT32, Cluster size (bytes): 32768
Files found (name date time size):
INPUT.BAS      2000-01-01 01:00:00 147
T012341.BAS   2017-06-21 16:55:28 146
BASIKA1.BAS   2017-06-21 16:55:36 146
Success!  Type any character to restart.
"

**Comment by DGxInfinitY** [comment]
@spairo1741 
For now, I am going to release a patch for the update because it appears that SD Support isn't working on setups other than my own, I still have yet to find the culprit so, for now, I would stick to EPROM and RAM because it does work for sure. Thanks for all the info, it really helps a lot!

Edit: A possible workaround, since you know sdfat works, would be to actually use that library, to do this you can edit the Arduino's source code on line 192 to `#include <sdfat.h>` or whatever include you need to use the library you want. This might just fix it but I recommend not using sdfat and just using the standard sd library, you could probably fix things by editing the sd card parameters(or add more) under that line, such as the chip select.

**Comment by spairo1741** [comment]
After the SD card initialization is properly initialized, the program does not display the contents of the card after the FILES command is given. I moved the cmd_Files structure to listfiles.ino from the SD directory.
SD directory was made after uploading library from TeensyduinoInstall137beta4.exe.
The cmd_files structure works fine in this program.
TinyBasicPlus teensy blocks read / write from SD card.
> Initializing SD card from listfiles.ino .initialization done.
    7753696.DAT      10485760
    7743456.DAT      10485760
    DEFAULT.TXT      0
    CALLBACK.TXT     1
    STAMP.TXT        0
    APPEND.TXT       686000
    AVG_TEST.TXT     1757
    BENCH.DAT        5000000
    LOGS/            (dir)
    FGETS.TXT        40
    GETLINE.TXT      69
    BENCH.TXT        149000
    RAW.TXT          5120000
    3V_FILE.CSV      45
    TEST.TXT         36
    TEST_SD.TXT      7
    SIZE_TST.TXT     7
    DIR1/            (dir)
    1.BAS            0
> 
from TinyBasicPlusTeensy

> HELLO
Teensy TinyBASICPlus v1.1
SD card init Ok.
57311 bytes free.
2048 EEProm bytes total.
OK
files
no file
OK
>

**Comment by spairo1741** [comment]
Finally, SD card, load and files is working.
Does not work save.
I had to lock sd.remove ((char *) filename in line probably 1852.
Also a low RAM message appears.
in the SD directory has been unlocked:

#define USE_TEENSY3_OPTIMIZED_CODE and changed
#define SD_CACHE_SIZE 2 // each cache entry uses 520 bytes of RAM
In the file SD_t3.h.
p.s.
//  #define LEDPIN 13
on console:

> Global variables use 63600 bytes (97%) of dynamic memory, leaving 1936 bytes for local variables. Maximum is 65536 bytes.
Low memory available, stability problems may occur.
> 

logs:

> HELLO
Teensy TinyBASICPlus v1.1
SD card init Ok.
57311 bytes free.
2048 EEProm bytes total.
OK
>files
    7753696.DAT      10485760
    7743456.DAT      10485760
    DATALOG.TXT      45305
    EXAMPLE.TXT      0
    TEST9999.TXT     18
    12345678.BAS     0
    7753696.DAT      10485760
OK
>eload
>save A1234.bas
OK
>files
    7753696.DAT      10485760
    7743456.DAT      10485760
    DATALOG.TXT      45305
    EXAMPLE.TXT      0
    TEST9999.TXT     18
    12345678.BAS     0
    7753696.DAT      10485760
OK
>load datalog.txt
>list
47 ,142,202
57 ,129,168
.......
352 ,253,252
OK

>

**Comment by DGxInfinitY** [comment]
By your log I would try the newest version and then try your patches again. Then see if the SD Card works. Very good progress, it's always cool to see what you find out.

**Comment by DGxInfinitY** [comment]
@spairo1741 Here is the video you asked for my man, sorry it took so long, not super easy on Linux but once you have the right tools you can get into the scheme of things and get it done. Thanks so much for all that you've done so far man!
https://youtu.be/jSefnDMmit8

**Comment by spairo1741** [comment]
Thank you for producing the film many things have been explained in it. It will be helpful for new users TBPlus and Teensy

**Comment by spairo1741** [comment]
So far, the problem has been solved by using SPI software and SdFat library. SAVE, LOAD FILES commands work.

HELLO
Teensy TinyBASICPlus v1.1
SD card init Ok.
57311 bytes free.
2048 EEProm bytes total.
OK
>files
2017-07-04 19:01:20        119 TEST.TXT
2000-01-01 01:00:00        637 TEST1.TXT
2000-01-01 01:00:00    5120000 RAWWRITE.TXT
2000-01-01 01:00:00         73 testfile.csv
2000-01-01 01:00:00     100000 print.txt
2000-01-01 01:00:00          0 dir2/
2000-01-01 01:00:00          7 stream.txt
2014-11-11 04:05:06          0 stamp.txt
2000-01-01 01:00:00          0 DIR1/
OK
>eload
>save tiny2.bas
OK
>files
2017-07-04 19:01:20        119 TEST.TXT
2000-01-01 01:00:00        137 TINY2.BAS
2000-01-01 01:00:00        637 TEST1.TXT
2000-01-01 01:00:00    5120000 RAWWRITE.TXT
2000-01-01 01:00:00         73 testfile.csv
2000-01-01 01:00:00     100000 print.txt
2000-01-01 01:00:00          0 dir2/
2000-01-01 01:00:00          7 stream.txt
2014-11-11 04:05:06          0 stamp.txt
2000-01-01 01:00:00          0 DIR1/
OK
>new
>load tiny2.bas
>list
5 TONE 10,1000
10 A=10
15 REC 1, 120
20 INPUT Z
30 Y = 120
40 PRINT A+Z
44 CHP Z/100
50 TONE 5, 300
55 REC 5000, 120
60 GOTO 5
OK

**Comment by DGxInfinitY** [comment]
Sweet, could you create a comment explaining all the things you did exactly for new users.

**Comment by spairo1741** [comment]
Currently working on timestamp for newly saved files. As I will elaborate, I will include all required corrections.

**Comment by spairo1741** [comment]
HELLO
Teensy TinyBASICPlus v1.3.1
57636 bytes free.
2048 EEProm bytes total.
OK
>files
2017-07-04 19:01:20        119 TEST.TXT
2000-01-01 01:00:00        137 TINY2.BAS
2000-01-01 01:00:00        637 TEST1.TXT
2017-07-06 04:05:06        137 QAZ.BAS
2017-07-06 04:05:06        137 WXY123.BAS
2000-01-01 01:00:00        137 ARDUINO3.BAS
2000-01-01 01:00:00         73 testfile.csv
2000-01-01 01:00:00          0 dir2/
2017-07-06 04:05:06          7 stream.txt
2000-01-01 01:00:00          0 DIR1/
OK

**Comment by spairo1741** [comment]
dowload library SdFat from this link
- https://git.defproc.co.uk/ea/inter-micro/tree/76cfd77c3ce24ccfe612691c15806baf2a1dbf78/libs
or SdFatCopy from this link
- https://github.com/eleciawhite/fed

make change:

125 //#define LEDPIN 13
192 #include <SPI.h> 				// needed as of 1.5 beta
193 // #include <SD.h>
194 #include <SdFat.h>
195 SdFat SD;

2139 	pinMode(10, OUTPUT); 							// change this to 53 on a mega
2140 	pinMode(10, HIGH); 

1977 	/*
			pinMode(13, OUTPUT);
			digitalWrite(LEDPIN, HIGH);
			  delay(500);
			  digitalWrite(LEDPIN, LOW);	
			  delay(500);	
			  digitalWrite(LEDPIN, HIGH);
			  */
				
in cmd_files remove from

2164			  while( true ) {
				    File entry = dir.openNextFile();
..... to line 2194.

add: 
		void cmd_Files( void )
		{
				File dir = SD.open( "/" );
			        dir.seek(0);
				dir.ls(LS_DATE | LS_SIZE); 	// date and size, name
				 dir.close();
		}	//----------------------------- cmd_Files -------------------------------
	#endif	
				
	change in SdFatconfig.h

81 #define SD_SPI_CONFIGURATION 2	
good luck.

**Comment by spairo1741** [comment]
> >time 2017 07 08 17 48 00
OK
>files
2017-07-08 16:33:58          0 _BAS/
2017-07-08 17:47:26        137 TM.BAS
2017-06-21 15:45:22        276 KREGOSLU.BAS
2017-06-21 15:47:44        326 LOKIEC.BAS
2017-06-21 15:49:44        182 SHUMANA.BAS
2017-07-08 17:47:46        137 QAZ.BAS
2017-07-08 17:48:06        137 T1.BAS
2017-07-08 17:52:24        137 1.BAS
2017-06-21 15:45:00        125 TOMEK3.BAS
2017-06-21 15:53:02        345 WYJSCIE.BAS
2000-01-01 01:00:00        244 _KREGI.BAS
2000-01-01 01:00:00        109 AUTORUN.BAS
2000-01-01 01:00:00        147 DATALOG.TXT
OK
>erase datalog.txt
OK
>files
2017-07-08 16:33:58          0 _BAS/
2017-07-08 17:47:26        137 TM.BAS
2017-06-21 15:45:22        276 KREGOSLU.BAS
2017-06-21 15:47:44        326 LOKIEC.BAS
2017-06-21 15:49:44        182 SHUMANA.BAS
2017-07-08 17:47:46        137 QAZ.BAS
2017-07-08 17:48:06        137 T1.BAS
2017-07-08 17:52:24        137 1.BAS
2017-06-21 15:45:00        125 TOMEK3.BAS
2017-06-21 15:53:02        345 WYJSCIE.BAS
2000-01-01 01:00:00        244 _KREGI.BAS
2000-01-01 01:00:00        109 AUTORUN.BAS
OK
>save baby.txt
2017-07-0818:49:44OK
>files
2017-07-08 18:49:44          0 BABY.TXT
2017-07-08 16:33:58          0 _BAS/
2017-07-08 17:47:26        137 TM.BAS
2017-06-21 15:45:22        276 KREGOSLU.BAS
2017-06-21 15:47:44        326 LOKIEC.BAS
2017-06-21 15:49:44        182 SHUMANA.BAS
2017-07-08 17:47:46        137 QAZ.BAS
2017-07-08 17:48:06        137 T1.BAS
2017-07-08 17:52:24        137 1.BAS
2017-06-21 15:45:00        125 TOMEK3.BAS
2017-06-21 15:53:02        345 WYJSCIE.BAS
2000-01-01 01:00:00        244 _KREGI.BAS
2000-01-01 01:00:00        109 AUTORUN.BAS
OK

>

**Comment by spairo1741** [comment]
> 
OK
>diag

type any character to start

init time: 0 ms
Card type: SDHC
Manufacturer ID: 3
OEM ID: SD
Product: SS08G
Version: 8.0
Serial number: 9f2d4fc4
Manufacturing date: 2/2010

cardSize: 7948.21 MB (MB = 1,000,000 bytes)
flashEraseSize: 128 blocks
eraseSingleBlock: true
OCR: c0ff8000

SD Partition Table
part,boot,type,start,length
1, 0,b, 8192, 15515648
2,0,0,0,0
3,0,0,0,0
4,0,0,0,0

Volume is FAT32
blocksPerCluster: 64
clusterCount: 242304
freeClusters: 242276
freeSpace: 7938.90 MB (MB = 1,000,000 bytes)
fatStartBlock: 12596
fatCount: 2
blocksPerFat: 1894
rootDirStart: 2
dataStartBlock: 16384
OK
>

**Comment by spairo1741** [comment]
> time 2017,7,10,       11,     21,                34
OK
>save
2017-07-1011:21:48 
OK
>
